name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish

    # Allows the action to write to the repository (git push)
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Setup necessary dotnet SDKs
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Build
        run: ./build.sh docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-deploys
