name: Client

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/Docs/**'
      - '.github/workflows/Docs.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup yarn
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: --version

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet run PublishDocs

      - name: Publish Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: publish/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
